yonainthefish/MoMoo

src/components/Button.tsx
feat/button -> main
공통으로 사용되는 button 컴포넌트 제작했습니다. 
버튼은 총 4가지 크기에 맞춰서 제작했습니다. 피그마 참고하여 사용해주세요
버튼 컴포넌트 사용시 size, props 받아와서 작업하시면 됩니다.
=> :bulb:Feat: 버튼 컴포넌트 제작(#1)

src/App.tsx, src/components/common/StyledInput.tsx, src/pages/Login.tsx
Design/input -> main
input 공통 스타일 구현
패딩 등 공통되지 않는 스타일은 구현하지 않아서, 확장해서 사용해주세요:)
=> :art: Design: input 공통 스타일 구현(#1)

src/components/Button/Button.tsx, src/components/Button/RadioButton.tsx, tsconfig.json
feat/button -> main
기존 버튼 컴포넌트와 기능에 차이가 있어서 분리하여 라디오버튼 형태로 컴포넌트 작업진행했습니다.
=> 🎨 Design: Button 공통 스타일 구현(#1)

src/components/Accordion/AccordionStyle.tsx, src/pages/Signup.tsx, src/pages/Upload/UploadStyle.tsx
Design/upload -> main
불필요한 주석 제거 및 textarea 중복 스크롤 스타일 수정했습니다.
=> 🎨 Design: Upload 스타일 구현(#4)

src/components/Modal/SelectModal.tsx, src/pages/Detail/Detail.tsx, src/pages/Detail/DetailStyle.tsx
Design/Detail -> main
- 게시글 상세 페이지 pc 사이즈 UI 작업 완료
- aria-labelledby 사용과 usEffect 를 이용하여 모달안에서 tap키 이동가능하도록  웹접근성 고려한 더보기 모달 작업 완료
=> 🎨게시글 상세 페이지 UI, 더보기 모달 구현 #15

src/hooks/useDeleteId.ts, src/hooks/useReauthenticate.ts, src/pages/Setting/Setting.tsx
Feat/deleteId -> main
- 회원탈퇴 기능
- 계정 인증 실패 시, 프로필 변경(이메일/비밀번호 변경, 회원탈퇴)을 중단하도록 수정
- 회원탈퇴 성공 시, 스플래시 혹은 로그인으로 이동하는 기능은 app.jsx에서 관리하기!
=> Feat: 회원탈퇴

src/GlobalStyle.tsx, src/components/Breadcrumb/Breadcrumb.tsx, src/components/Breadcrumb/BreadcrumbWrap.tsx, src/components/Breadcrumb/StyledBreadcrumb.ts, src/components/Breadcrumb/StyledBreadcrumbWrap.ts, src/components/StyledAuth.ts, src/pages/Login.tsx, src/pages/Setting/Setting.tsx, src/pages/Setting/StyledMain.ts, src/pages/Signup.tsx
Design/setting -> main
- 세팅페이지 브레드크럼 추가
- 브레드크럼 컴포넌트로 분리
=> design: 브레드크럼

src/asset/icon/Logout.svg, src/components/MyPopup/MyPopup.tsx, src/components/Nav/Nav.tsx, src/hooks/useLogout.ts
Feat/my -> main
로그아웃, 닫기 기능 추가
=> :bulb: Feat: 로그아웃, 닫기 기능 추가(#42)

src/App.tsx, src/Routes/AuthRoute.tsx, src/Routes/NavRoute.tsx, src/Routes/Router.tsx, src/hooks/useLogin.ts, src/main.tsx, src/pages/Home/Home.tsx, src/pages/Login.tsx
Feat/routing -> main
- 로그인 여부에   따른 라우팅
- 라우팅을 위해 홈 컴포넌트 파일 생성
=> 💡 Feat: 로그인 여부에   따른 라우팅(#45)

src/Routes/Router.tsx, src/components/Nav/Nav.tsx, src/components/Nav/StyledNav.ts, src/components/Upload/Upload.tsx, src/components/Upload/UploadStyle.tsx
feat/upload -> main
네비바 임시 작업 후 모달 작동 구현 했습니다, 
router에 필요없는 코드 삭제 했습니다.
=> 💡 Feat: nav 버튼 작동 구현 

src/components/Modal/AlertModal.tsx, src/components/Modal/ArrayModal.tsx, src/components/Modal/LocationSelectModal.tsx, src/components/Modal/NewAlbumModal.tsx
ex) Design/modal -> main
modal 공통 스타일링 완료했습니다
=> :art: Design: modal 공통 스타일 구현(#1)

src/asset/icon/X-White.svg, src/components/Map/KakaoMap.tsx, src/components/Nav/Nav.tsx, src/components/Nav/StyledNav.ts, src/components/Upload/Upload.tsx, src/components/Upload/UploadStyle.tsx
Design/upload -> main
위치 추가 토글시 업로드의 모달 길이가 늘어나는 부분 수정했습니다.
=> ♻️ Refactor: 게시글 사진 업로드 모바일 UI 수정

src/components/Nav/StyledNav.ts, src/pages/Detail/Detail.tsx, src/pages/Detail/DetailStyle.tsx
Design/Detail -> main
- 게시물 상세 페이지 브래드 크럼 수정 및 변경 디자인 적용
- 네브 positon : relative -> fixed 로 수정
=> :art: Design: 게시글상세 마크업 수정 & 네브 position 변경

src/hooks/useSetUserCollection.ts, src/hooks/useSingup.ts, src/pages/Login.tsx, src/pages/Signup.tsx
Feat/createCollection -> main
- Fix: error state 변경 시, 경고 문구가 렌더링 되도록 수정 
- Refactor: than catch 중첩 풀기
- Feat: 유저 컬렉션 생성
=> Feat: 유저 컬렉션 생성

src/hooks/useLogin.ts
Refactor/useLogin
:recycle: Refactor: trycatch로 수정(#32)
=> :recycle: Refactor: trycatch로 수정(#32)

src/components/Album/Album.tsx, src/components/Modal/ArrayModal.tsx, src/components/Nav/StyledNav.ts, src/components/StyledH2.ts, src/components/TabBar/StyledTabBar.ts, src/pages/Home/Home.tsx, src/pages/Home/StyledHomeSection.ts, src/pages/Home/StyledMain.ts
ex) Design/home -> main
ex) 홈피드 UI 구현했습니다
=> :art: Design:홈피드 UI 구현(#65)

src/components/Accordion/Accordion.tsx, src/components/FileUpload/Preview.tsx, src/components/Map/KakaoMap.tsx, src/components/Upload/Upload.tsx, src/components/Upload/UploadStyle.tsx
feat/upload-> main
업로드시 저장하는 정보 앨범종류 외 모두 저장하도록 담았습니다. 
게시물 작성 후 업로드시 uid로 구분된 컬렉션 -> feed -> feedList -> uploadData의 객체로 하나씩 담깁니다. 
+ 추가적으로 앨범종류 받아온 뒤 선택하는 내용이 파이어베이스에 저장되어야 합니다.
=> 💡 Feat: 게시물 업로드 정보 파이어베이스 저장

src/Routes/NavRoute.tsx, src/components/Album/Album.tsx, src/components/Modal/ArrayModal.tsx, src/components/Nav/StyledNav.ts, src/pages/Home/Home.tsx, src/pages/Home/StyledHomeSection.ts
ex) Feat/home -> main
모바일 너비시 탑 네비 추가 ,Nav와 TabBar같이 나오게 NavRoute 수정
Album 공통 컴포넌트 백그라운드 이미지 추가
홈 모달버튼 클릭시 모달나오게 추가
=> :art: Design: 홈피드 UI 추가(#65)

src/components/FileUpload/Preview.tsx, src/components/Upload/Upload.tsx
feat/upload-> main
게시물 업로드시 uuid 활용하여 고유 id 추가 하고 데이터 저장 되도록 기능 추가 했습니다.
=> :bulb: Feat: 게시물 id 생성 및 데이터 저장 

src/pages/Album/Album.tsx
Feat/albumDetail -> main
:bulb: Feat: 앨범 상세페이지 앨범병 동적 렌더링(#76)
=> :bulb: Feat: 앨범 상세페이지 앨범병 동적 렌더링(#76)

package-lock.json, package.json, src/pages/Album/Album.tsx, src/pages/Album/StyledGridFeed.ts, src/pages/Album/StyledMain.ts
Feat/albumDetail -> main
:art: Design: 앨범 상세페이지 리스트형 제거(#75)
=> :art: Design: 앨범 상세페이지 리스트형 제거(#75)

src/components/Modal/NewAlbumModal.tsx, src/hooks/useAddAlbum.ts
ex) Feat/home -> main
새로운 앨범을 추가했을때 파이어베이스에 uid-uid-album-(앨범명)-{feedList[ ],createdTime} 플로우로 저장 됩니다
=> :bulb: Feat: 홈피드 앨범 추가 기능(#79)

src/hooks/useAddAlbum.ts
ex) Feat/home -> main
파이어베이스에 uid-uid-album-무작위변수-{feedList[ ],createdTime,name} 플로우로 저장 됩니다
=> :bug: Fix: 앨범 이름  파이어베이스 저장 방식 변경(#79)

src/components/FileUpload/Preview.tsx, src/components/Upload/Upload.tsx, src/components/Upload/UploadImageToStorage.tsx
feat/upload-> main
- 변경된 문서 구조대로 저장되도록 수정했습니다.
- 이미지 다중선택 후 업로드시 배열로 url 받아오도록 수정했습니다.
=> :recycle: Refactor: 파이어베이스 문서 구조 수정, 이미지 다중선택 url 배열 추가 (#72)

src/components/Modal/NewAlbumModal.tsx, src/hooks/useAddAlbum.ts, src/hooks/useSingup.ts
Feat/createAllFeedsDoc -> main
:bulb: Feat: 회원가입 시, 전체 보기 앨범 생성
=> :bulb: Feat: 회원가입 시, 전체 보기 앨범 생성(#88)

src/components/StyledAuth.ts, src/components/StyledH2.ts, src/pages/Setting/Setting.tsx, src/pages/Setting/StyledMain.ts
Design/auth -> main
:art: Design: 로그인/회원가입/세팅 페이지 UI 깨짐 수정
=> :art: Design: 로그인/회원가입/세팅 페이지 UI 깨짐 수정

src/components/Upload/Upload.tsx
feat/upload -> main
- 기존에 배열로 저장되던 데이터 저장 구조 변경 했습니다.  
- 업로드 후 id에 따라 페이지 이동하도록 추가했습니다.
=> :bulb:feat: 업로드시 데이터 저장 구조 변경 및 페이지 이동 추가(#59)

src/App.tsx, src/components/FileUpload/Preview.tsx, src/components/ListFeed/ListFeed.tsx, src/components/Modal/SelectModal.tsx, src/components/Upload/EditFeed.tsx, src/components/Upload/accordionData.ts, src/context/EditContext.tsx, src/hooks/useEditContext.ts, src/hooks/useEditFeed.ts, src/hooks/useGetFeedData.ts, src/main.tsx, src/pages/Album/GridFeed.tsx
Feat/editFeed -> main
Feat: 게시글 수정 기능 추가
=> :bulb: Feat: 게시글 수정 기능 추가(#57)

src/App.tsx, src/asset/icon/Arrow-White.svg, src/asset/icon/ArrowLeft.svg, src/asset/icon/ArrowRight.svg, src/components/FileUpload/Preview.tsx, src/components/ListFeed/StyledListFeed.ts, src/components/Nav/Nav.tsx, src/components/Nav/StyledNav.ts, src/components/Upload/EditFeed.tsx, src/components/Upload/StyledOverlay.ts, src/components/Upload/Upload.tsx, src/components/Upload/UploadStyle.tsx, src/pages/Detail/Detail.tsx, src/pages/Detail/DetailStyle.tsx
Design/editFeed -> main
🎨 Design: overlay 컴포넌트 분리
🎨 Design: 게시물 상세 UI 깨짐 수정
🎨 Design: 업로드 모달 인디케이터, 다음/이전 버튼 디자인 변경
=> Design: 게시글 상세, 업로드 모달 UI

src/components/Accordion/Accordion.tsx, src/components/Accordion/AccordionStyle.tsx, src/components/Accordion/MultipleAccordion.tsx, src/components/Upload/Upload.tsx, src/components/Upload/accordionData.ts
feat/upload-> main
업로드 모달작동 방식이 다른 앨범선택과 오늘의기분, 오늘의 날씨 컴포넌트를 MulitArccodion 과 Accordion으로 분리
=> 💡 Feat: 게시물 업로드 데이터 분리 #59

src/components/Album/Album.tsx, src/components/Modal/ArrayModal.tsx, src/components/Modal/DeleteAlbumModal.tsx, src/hooks/useGetAlbumList.ts, src/pages/Home/Home.tsx, src/pages/Home/StyledHomeSection.ts
ex) Feat/home-> main
- 앨범 삭제, 앨범 변경 모달 디자인 
- 파이어베이스에 데이터 받아와서 홈피드에 뿌려주기
- 최신순 오래된순 정렬기능
=> :bulb: Feat: 데이터 홈피드 대입,정렬기능 추가 (#106)

src/App.tsx, src/Routes/AuthRoute.tsx, src/components/Nav/Nav.tsx, src/components/TabBar/TabBar.tsx, src/components/Upload/Upload.tsx, src/context/UploadContext.tsx, src/hooks/useUploadContext.ts, src/main.tsx, src/pages/Album/Album.tsx, src/pages/Detail/Detail.tsx
Feat/albumDetail -> main
Feat: 앨범 상세 새 게시물 모달 띄우기 / 업로드 컨텍스트 생성 및 적용
=> :bulb: Feat: 앨범 상세 새 게시물 모달 띄우기 / 업로드 컨텍스트 생성 및 적용(#56)

src/components/Upload/Upload.tsx, src/components/Upload/UploadStyle.tsx
Design/upload -> main
Design: 업로드 모달 헤더 UI 깨짐 수정
=> Design: 업로드 모달 헤더 UI 깨짐 수정

src/components/Topbar/StyledTopbar.ts, src/pages/Setting/Setting.tsx, src/pages/Setting/StyledMain.ts
Feat/my -> main
Feat: 세팅페이지 모바일 회원탈퇴 기능 적용 및 UI 깨짐 수정
=> Feat: 세팅페이지 모바일 회원탈퇴 기능 적용 및 UI 깨짐 수정

src/components/Accordion/Accordion.tsx, src/components/Accordion/MultipleAccordion.tsx, src/components/Album/Album.tsx, src/components/Upload/EditFeed.tsx, src/components/Upload/Upload.tsx, src/hooks/useGetSavedAlbumList.ts, src/hooks/useUpdateFeedList.ts
Feat/editFeed -> main
Feat: 게시물 수정 모달 앨범 선택 기능 추가
=> :bulb: Feat: 게시물 수정 모달 앨범 선택 기능 추가

src/components/Upload/accordionData.ts, src/hooks/useGetAlbumList.ts, src/pages/Home/Home.tsx
Feat/editFeed -> main
Refactor: 게시물 모달 앨범 데이터 불러오기 훅 재사용하도록 수정
=> Refactor: 게시물 모달 앨범 데이터 불러오기 훅 재사용하도록 수정

src/components/FeedItem/FeedItem.tsx, src/components/FeedItem/StyledFeedItem.ts, src/components/Upload/accordionData.ts, src/pages/Detail/Detail.tsx
Feat/editFeed -> main
게시글 상세 -> 더보기 -> 게시글 수정 모달
수정할 게시글 정보가 불러와지지 않은 오류
원인: 게시글 상세에서 더보기 모달로 임시 feed Id 전달
해결:  주소 파라미터(feed Id) 전달
=>  Fix: 게시물 상세 -> 더보기 모달로 feed id 전달

src/components/Upload/accordionData.ts, src/hooks/useGetAlbumList.ts, src/pages/Home/Home.tsx
=> Feat: 앨범 정렬 기능

src/components/Album/Album.tsx, src/components/FeedItem/FeedItem.tsx, src/components/Modal/AlertModal.tsx, src/components/Modal/SelectModal.tsx, src/components/Upload/EditFeed.tsx, src/components/Upload/Upload.tsx, src/hooks/useUpdateFeedList.ts
feat/deleteFeed -> main
- 홈 -> 게시글 상세로 넘어 가지 않는 경로 오류 수정
- 카멜케이스 오류 변수명 수정
- 게시글 삭제시 feed, album에서 모두 삭제되도록 기능 추가
=> :bulb: Feat: 게시물 삭제 기능

src/components/Album/Album.tsx, src/components/FeedItem/FeedItem.tsx, src/components/Modal/DeleteAlbumModal.tsx, src/hooks/useDeleteAlbum.ts, src/hooks/useEditAlbum.ts, src/hooks/useGetAlbumList.ts
ex) Feat/home -> main
- 앨범명 수정,삭제기능
- 전체보기 앨범은 삭제및 앨범명 수정 불가하게 구현
-  albumDataList.push({ ...doc.data(), id: doc.id }) id를 추가로 넣어줘서 같은 아이디의 문서를 삭제 수정할수있도록 구현
=> :bulb: Feat: 앨범명 수정,삭제기능(#106)

src/App.tsx, src/components/Album/Album.tsx, src/components/Upload/EditFeed.tsx, src/context/PageContext.tsx, src/hooks/usePageContext.ts, src/pages/Album/Album.tsx, src/pages/Album/FeedItem.tsx, src/pages/Detail/Detail.tsx
Feat/FeedDetail
Fix: 피드/앨범 디테일 브레드크럼 클릭 시, 라우팅 수정
=> Fix: 피드/앨범 디테일 브레드크럼 클릭 시, 라우팅 수정

src/components/FeedItem/FeedItem.tsx, src/components/Modal/AlertModal.tsx, src/components/Modal/ChangeAlbumModal.tsx, src/components/Modal/SelectModal.tsx
feat/feleteFeed -> main
- 게시글 앨범 변경 추가
- 앨범 변경 2회시 들어갈 때 발생하는 오류 수정
=> :bulb: Feat: 게시글 변경 모달 앨범 변경 기능 (#82)

src/components/Accordion/Accordion.tsx, src/components/Accordion/AccordionStyle.tsx, src/components/Accordion/MultipleAccordion.tsx, src/components/FeedItem/FeedItem.tsx, src/components/FeedItem/StyledFeedItem.ts, src/components/FileUpload/Preview.tsx, src/components/Modal/AlertModal.tsx, src/components/Modal/ArrayModal.tsx, src/components/Modal/SelectModal.tsx, src/components/TabBar/StyledTabBar.ts, src/components/Upload/EditFeed.tsx, src/components/Upload/Upload.tsx, src/components/Upload/UploadImageToStorage.tsx, src/context/EditContext.tsx, src/hooks/useEditFeed.ts, src/hooks/useUpdateFeedList.ts, src/pages/Album/FeedItem.tsx, src/pages/Home/Home.tsx
fix/upload-> main
의미없는 주석 제거 및 변수 오타 수정했습니다.
=> :lipstick: Style: 의미없는 주석 제거 및 오타 수정

src/pages/Home/StyledHome.ts
=> SyledHome파일 수정(#94)

src/components/Carousel/StyledCarousel.ts, src/components/FileUpload/StyledPreview.ts, src/components/MyPopup/StyledMyPopup.ts, src/components/Upload/EditFeed.tsx, src/components/Upload/Upload/StyledUpload.ts, src/hooks/useDeleteId.ts, src/pages/Detail/FeedItem/StyledFeedItem.ts, src/pages/My/StyledMy.ts, src/pages/Setting/Setting.tsx
Feat/deleteID -> main
- Feat: 계정 삭제 시, 유저 데이터 삭제
- Design: UI 깨짐 수정
*before
*after
- 스크롤이 필요할 때만 생기도록 overflow: scroll->auto로 수정
- 이미지 사이 간격 1rem(=10px) -> 1px로 수정
=> Feat: 계정 삭제 시, 유저 데이터 삭제 / Design: UI 깨짐 수정

src/components/FileUpload/Preview.tsx
Fix/feedModal -> main 
:bug: Fix: 게시물 모달, 이미지 개수 초과 alert 버그 수정(#151)
=> :bug: Fix: 게시물 모달, 이미지 개수 초과 alert 버그 수정(#151)

src/components/Upload/EditFeed.tsx, src/components/Upload/Upload/Upload.tsx, src/components/Upload/UploadImageToStorage.tsx
Fix/feedImgName -> main
:bug: Fix: 피드 이미지명 겹치지 않도록 수정(#124)
=> :bug: Fix: 피드 이미지명 겹치지 않도록 수정(#124)

src/components/Breadcrumb/Breadcrumb.tsx, src/components/Modal/AlertModal/AlertModal.tsx, src/pages/Album/Album.tsx, src/pages/Detail/FeedItem/FeedItem.tsx
Feat/deleteFeed -> main
- Feat: 게시물 삭제 시, storage에서 해당 이미지 삭제
- 버그 수정(커밋 참조)
=> Feat: 게시물 삭제 시, storage에서 해당 이미지 삭제 / Fix: 버그 수정

src/hooks/useGetAlbumFeedList.ts, src/pages/Album/Album.tsx, src/pages/Album/StyledAlbum.ts
Design/albumDetail -> main
커밋 참조
=> Design: UI 깨짐 수정

src/components/Upload/GetAccordionData.ts, src/components/Upload/Upload/Upload.tsx
- [x] 버그 수정
fix/uploadModal -> main
- 업로드시 랜더린 되는 앨범 없던 오류 수정했습니다.
=> :bug: Fix: 랜더링 되는 앨범리스트 없는 오류 수정(#134)

src/components/Upload/EditFeed.tsx, src/pages/Detail/FeedItem/FeedItem.tsx
refector/common -> main
interface 위치 통일
=> :recycle: Refactor: interface 사용 통일(#147)

src/components/Upload/GetAccordionData.ts
fix/uploadModal -> main
이미지 경로 오류 수정 했습니다.
=> :bug: Fix: 이미지 경로 오류 수정(#167)

src/asset/icon/Loading.svg, src/asset/icon/LoadingBlack.svg, src/components/Button/Button/StyledButton.ts, src/components/Loading/StyledLodingImg.ts, src/hooks/useReauthenticate.ts, src/pages/Setting/Setting.tsx
ex) feat/login -> dev
- Design: 세팅 페이지 - 프로필 변경 로딩중 UI 추가
- 버튼 컴포넌트에 로딩 중 img 스타일 추가
- 로딩 중 svg 변경(여백 제거한 이미지로) 및 추가
=> :art: Design: 세팅 페이지 - 프로필 변경 로딩중 UI 추가

src/components/Album/Album.tsx, src/components/Album/StyledAlbum.ts, src/components/Modal/SelectModal/StyledSelectModal.ts
ex) Feat/login -> main
모달 스타일 margin-bottom 값 수정, 스타일 컴포넌트 props 값 앞에 $  추가
=> :recycle: Refactor:모달 스타일 수정, 스타일 컴포넌트 props 값 수정 (#172)

src/components/Modal/AlertModal/AlertModal.tsx, src/components/Modal/AlertModal/StyledAlertModal.ts, src/hooks/useReauthenticate.ts, src/pages/Detail/FeedItem/DeleteFeedModal.tsx, src/pages/Detail/FeedItem/FeedItem.tsx, src/pages/Setting/DeleteIdModal.tsx, src/pages/Setting/Setting.tsx
Design/alertModal
- 회원 탈퇴 시, 대화 상자를 window.confirm()에서 디자인된 AlertModal로 변경
- 모달 컴포넌트를 분리하여 재사용 함
=> Refactor: 회원 탈퇴 시, alert를 디자인된 모달로 변경 및 모달 컴포넌트 분리

src/pages/Setting/Setting.tsx
Design/alertModal -> main
- Fix: 회원 탈퇴 -> 비밀번호 재인증 -> 실패 alert 중복 수정
=> Fix: 회원 탈퇴 -> 비밀번호 재인증 -> 실패 alert 중복 수정

src/components/Modal/Loading/Loading.tsx, src/components/Modal/Loading/StyledLoadingModal.ts, src/hooks/useDeleteId.ts, src/pages/Setting/DeleteIdModal.tsx, src/pages/Setting/Setting.tsx
Design/loading -> main
- Feat: 회원탈퇴 로딩중 상태 추가
- Design: 로딩중 모달 컴포넌트 추가/회원 탈퇴 중 조건부 렌더링 추가
- Fix: 회원 탈퇴 시, 비밀번호 재인증 중 save 버튼이 로딩중이 되는 버그 수정
=> Design: 로딩중 모달 컴포넌트 추가/회원 탈퇴 중 조건부 렌더링 추가

src/pages/Policy/PrivacyPolicy.tsx, src/pages/Policy/StyledPolicy.ts, src/pages/Policy/Terms.tsx
Design/policy -> main
Design: 이용약관 페이지 UI 수정
=> Design: 이용약관 페이지 UI 수정

src/pages/Detail/FeedItem/FeedItem.tsx
Design/feed -> main
:art: Design: 피드 상세 - 텍스트 줄바꿈 적용
=> :art: Design: 피드 상세 - 텍스트 줄바꿈 적용

src/Routes/Router.tsx, src/asset/icon/ArrowRight.svg, src/asset/icon/Checkbox.svg, src/asset/icon/CheckboxChecked.svg, src/components/CommonStyled/StyledAuth.ts, src/components/Nav/Nav.tsx, src/pages/Signup/Signup.tsx, src/pages/Signup/StyledSignup.ts
Design/signup -> main
- 동의 항목 UI 적용
- Signup 버튼 - 여백, border-top 추가
- nav 중단점 오타 수정
- 동의 항목 링크 연결
=> Design: 회원가입 - 동의항목 및 Signup 버튼 UI 수정

src/pages/Signup/Signup.tsx, src/pages/Signup/StyledSignup.ts
Fix/agree -> main
- Fix: 전체 동의 클릭 영역 수정
- Refactor: 불필요한 이미지 태그 background로 변경
*이전 영역 이슈 참고
=> Fix: 전체 동의 클릭 영역 수정/ Refactor: 불필요한 이미지 태그 background로 변경

src/pages/Detail/StyledDetail.ts
Refactor/feed -> main
Refactor: 게시물 상세 - UI 사이즈 버그
=> Refactor: 게시물 상세 - UI 사이즈 버그

src/Routes/Router.tsx
Fix/route -> main
Fix: my 페이지, 404 페이지 라우트 버그 수정
=> Fix: my 페이지, 404 페이지 라우트 버그 수정

src/components/CommonStyled/StyledModalOverlay.ts, src/components/Upload/Upload/StyledUpload.ts, src/pages/Setting/Setting.tsx
=> Fix: 탑바 버그 수정

package-lock.json, package.json, src/main.tsx, src/pages/Album/Album.tsx, src/pages/Detail/Detail.tsx, src/pages/Home/Home.tsx, src/pages/Login.tsx, src/pages/My/My.tsx, src/pages/Policy/PrivacyPolicy.tsx, src/pages/Policy/Terms.tsx, src/pages/Setting/Setting.tsx, src/pages/Signup/Signup.tsx
Feat/title -> main
- Feat: 각 페이지별 title 변경(#162)
=> Feat: 각 페이지별 title 변경

src/components/FileUpload/Preview.tsx
fix/uploadModal -> main
- 2MB 의 제한 사항에서 10MB로 용량을 늘렸습니다.
- 제한된 용량 이상의 이미지를 업로드할 때 alert 모달은 뜨지만 업로드되는 오류 수정했습니다.
=> :bug: Fix: 이미지 용량수정 및 용량제한 경고 후 업로드 되는 오류 수정(#187)

index.html
Feat/analytics -> main
-Feat: 애널리틱스 코드 삽입
=> Feat: 애널리틱스 코드 삽입

src/components/Upload/Upload/StyledUpload.ts, src/pages/Home/MobileHeader.tsx, src/pages/Home/StyledHome.ts
ex) Refactor/home -> main
모바일로 업로드 화면에 접속할시 UploadHeader  부분이 짤려서 나오지 않는 현상 발생, 
모바일 화면시 position값을 fixed로 설정하여 화면 상단에 고정되게 구현
추가로 home 화면에 헤더부분은 position:fixed부분을 제거하여 스크롤시 같이 올라가는 구조로 변경
ex) 베이스 브랜치에 포함되기 위한 코드는 모두 정상적으로 동작해야 합니다. 결과물에 대한 스크린샷, GIF, 혹은 라이브 데모가 가능하도록 샘플API를 첨부할 수도 있습니다.
=> :bug: Fix: 모바일 헤더 숨겨짐 수정(#211)

src/hooks/useGetAlbumList.ts, src/pages/Home/Home.tsx
ex) Refactor/home ->main
기존의 oldestAlbumList가 최신순으로 정렬되는 이슈가있어서
이름을 latestAlbumList로 변경하고 기존의 albumDataList를 오래된순의 정렬리스트로 설정
=> :bug: Fix:홈-정렬기준 수정(#213)

src/Routes/Router.tsx, src/components/Modal/SelectModal/SelectModal.tsx, src/components/Nav/Nav.tsx, src/components/TabBar/TabBar.tsx, src/components/Upload/EditFeed.tsx, src/components/Upload/Upload/StyledUpload.ts, src/components/Upload/Upload/Upload.tsx, src/hooks/useEditFeed.ts, src/pages/Album/FeedItem.tsx, src/pages/Detail/FeedItem/FeedItem.tsx, src/pages/Edit.tsx, src/pages/Upload.tsx
Fix/upload -> main
- Fix: 게시물 모달 - 모바일에서 페이지로 변경
=> Fix: 게시물 모달 - 모바일에서 페이지로 변경

src/Routes/AuthRoute.tsx, src/components/Accordion/StyledAccordion.ts, src/components/FileUpload/Preview.tsx, src/components/FileUpload/StyledPreview.ts, src/components/Modal/ChangeAlbumModal/StyledChangeAlbumModal.ts, src/components/Upload/EditFeedModal.tsx, src/components/Upload/Upload/StyledUpload.ts, src/components/Upload/Upload/Upload.tsx, src/pages/Edit.tsx, src/pages/Upload.tsx
Fix/upload -> main
- Fix: 유효하지 않은 확장자 업로드 가능한 버그 수정
- Feat: 유효하지 않은 이미지 선택 시, 기존 이미지 유지
- Feat: 업로드 로딩중 UI 추가
- Design: 게시물 모달 캐러셀 - 이미지 비율 1/1로 수정(pc, tablet)
이미지 선택/미선택 시 높이 같도록 수정(mobile)
- Fix: 앨범 변경 - 선택 취소 시 UI 버그 수정
+ hover 색상 변경: selected 컬러보다 연한 색상으로
=> Fix: 게시물 모달 버그 수정

index.html, src/pages/Album/Album.tsx, src/pages/Upload.tsx
ex) feat/login -> dev
- Fix: 앨범 상세 - 모바일에서 새 게시물 클릭 시, 페이지로 연결
- style: 불필요한 코드 제거
- public은 경로에서 생략할 수 있다.
=> Fix: 앨범 상세 - 모바일에서 새 게시물 클릭 시, 페이지로 연결

package.json, src/App.tsx, src/Routes/AuthRoute.tsx, src/Routes/Router.tsx, src/components/Breadcrumb/Breadcrumb.tsx, src/components/Nav/Nav.tsx, src/components/TabBar/TabBar.tsx, src/pages/Album/Album.tsx, src/pages/Detail/Detail.tsx, src/pages/Policy/PrivacyPolicy.tsx, src/pages/Policy/Terms.tsx, src/pages/Setting/Setting.tsx, src/pages/Splash/Splash.tsx
Fix/router -> main
- 뒤로가기 클릭 시, 스플래시로 돌아가지 않도록 수정했습니다.
=> Fix: 뒤로가기 클릭 시, 스플래시로 돌아가지 않도록 수정

src/components/Modal/AlertModal/StyledAlertModal.ts, src/components/Modal/DeleteAlbumModal/DeleteAlbumModal.tsx, src/components/Modal/DeleteAlbumModal/StyledDeleteAlbumModal.ts, src/components/Modal/NewAlbumModal/StyledNewAlbumModal.ts
Fix/modal -> main
Fix: 모달 - 모달이 잘리는 버그 수정
에뮬레이터에서 글자 크기를 키웠을 때
=> Fix: 모달 - 모달이 잘리는 버그 수정

src/components/CommonStyled/StyledAuth.ts, src/components/CommonStyled/StyledInput.ts, src/components/Upload/Upload/StyledUpload.ts, src/pages/Album/StyledAlbum.ts
Design/fontColor -> main
Design: 텍스트 명암 대비 기준 충족
변경 후
변경 전
=> Design: 텍스트 명암 대비 기준 충족

src/components/CommonStyled/StyledAuth.ts, src/components/Modal/StyledInputModal.ts, src/pages/Setting/ReauthModal.tsx, src/pages/Setting/Setting.tsx
Design/Setting -> main
Design: 계정 재인증 alert -> 커스텀 모달
=> Design: 계정 재인증 alert -> 커스텀 모달

src/Routes/NavRoute.tsx, src/Routes/Router.tsx, src/components/Nav/Nav.tsx, src/pages/Error/Error.tsx, src/pages/Error/StyledError.ts
Fix/404 -> main
Fix: 404페이지 nav 컴포넌트 렌더링
=> Fix: 404페이지 nav 컴포넌트 렌더링

src/GlobalStyle.tsx, src/components/FileUpload/Preview.tsx, src/components/Modal/AlertModal/AlertModal.tsx, src/components/Modal/AlertModal/StyledAlertModal.ts, src/components/Modal/ConfirmModal/ConfirmModal.tsx, src/components/Modal/ConfirmModal/StyledConfirmModal.ts, src/components/Modal/StyledInputModal.ts, src/components/MyPopup/MyPopup.tsx, src/hooks/useLogout.ts, src/hooks/useSetProfileImage.ts, src/pages/Detail/FeedItem/DeleteFeedModal.tsx, src/pages/Login.tsx, src/pages/My/My.tsx, src/pages/Setting/DeleteIdModal.tsx, src/pages/Setting/Setting.tsx, src/pages/Signup/Signup.tsx, src/utils/SDKUtils.ts
ex) feat/login -> dev
- Design: 기존 AlertModal -> ConfirmModal / AlertModal 추가
- Design: 커스텀 alert로 변경
=> Design: 커스텀 alert로 변경

src/components/Modal/NewAlbumModal/StyledNewAlbumModal.ts, src/hooks/useDeleteAlbum.ts, src/hooks/useEditAlbum.ts, src/pages/Home/StyledHome.ts
ex) Refactor/home ->main
앨범 필터 버튼 mobile, tablet에도 원배경색 추가
InputModal UI 기본 여백 수정
=> Design: 홈 스타일 수정

src/components/Accordion/StyledAccordion.ts, src/components/Carousel/Carousel.tsx, src/components/FileUpload/Preview.tsx, src/components/FileUpload/StyledPreview.ts, src/components/Map/KakaoMap.tsx, src/components/Upload/EditFeedModal.tsx, src/components/Upload/GetAccordionData.ts, src/components/Upload/Upload/StyledUpload.ts, src/components/Upload/Upload/Upload.tsx, src/pages/Edit.tsx, src/pages/Upload.tsx
fix/upload -> dev
- PC, 테블릿, 모바일 업로드 모달 수정된 디자인으로 수정 완료
- 모바일 디바이스에서 스와이프 슬라이드 적용되도록 수정
- pr 확인 후 머지하면 main 브랜치로 옮기겠습니다~
=> Fix/upload 업로드모달 변경된 디자인으로 수정 및 모바일 디바이스에서 스와이프 슬라이드 사용할 수 있도록 수정
